### ISSUE TITLE
Incorrect project path

### ISSUE THREAD

**Issue by konraddysput** [game-ci/unity-actions#61]
**Describe the bug**
Hi. 

Thank you for your hard work! This project will definetly help a lot unity developers!

I tried to play around your solution. I'm maintainer of backtrace-unity package (https://github.com/backtrace-labs/backtrace-unity) and after multiple tests I wasn't able to build my package. This is what I get from my github action: 
```
Couldn't set project path to: /github/workspace/github/workspace/.
```

To make sure that I didn't do anything not expected - I copy pasted your github action. 

**To Reproduce**
- Go to pull request and see github action behavior: https://github.com/backtrace-labs/backtrace-unity/pull/14 

**Expected behavior**
LIbrary build and run unit tests correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/9386268/78989999-7daa0900-7b35-11ea-84b9-70841cf53f7e.png)

![image](https://user-images.githubusercontent.com/9386268/78989969-6e2ac000-7b35-11ea-9df6-df168eb0f21e.png)

**Additional context**
* In library root directory you can find project directories - in your case you needed to mv to test-project dir. I assume my project path should change or I shouldn't use project path at all? 
* Library is using .asmdef 
* Library has only runtime unit tests.

**Comment by DanielParra159** [comment]
Hi @konraddysput 

I just configured it on my project and had the same problem at the beginning but after set projectPath  to matrix it is working well, try to add this to matrix.

```
projectPath:
          - ./
```

Here you can look the complete file I'm using: [build.yml](https://github.com/DanielParra159/HangmanGame/blob/master/.github/workflows/build.yml)

**Comment by konraddysput** [comment]
@DanielParra159 

Good idea! After your suggestion I tried to apply run once again pipeline and unfortunatelly It didn't help me :( 


![image](https://user-images.githubusercontent.com/9386268/78995425-9836af00-7b42-11ea-9384-e15639f5ce9d.png)

**Comment by DanielParra159** [comment]
I'm checking your output with mine and I can see that your tests step is trying to use `/github/workspace/github/workspace/` instead of  `/github/workspace/`, but I don't know why, maybe you can try to use other Unity version to discard if is a problem with the image.
Probably is not the problem but you can remove the line with `customParameters`

**Comment by konraddysput** [comment]
@DanielParra159 still no luck :< I even copy pasted configuration from your project and still the same issue.

**Comment by webbertakken** [comment]
Looks like your first problem was resolved by @konraddysput suggestion as can be seen in your last check [here](https://github.com/backtrace-labs/backtrace-unity/pull/14/checks#step:4:152), indicated by the following:

```console
Using project path "/github/workspace/.".
```

Your output now gives a message about your license not being valid. Indicated [here](https://github.com/backtrace-labs/backtrace-unity/pull/14/checks#step:4:220) indicated by unity licensing module giving you the following feedback:

```console
[Licensing::Module] Successfully launched and connected to LicensingClient
Entitlement-based licensing initiated
[LicensingClient] Licenses Updated successfully in LicensingClient

LICENSE SYSTEM [2020410 11:1:24] Next license update check is after 2019-11-25T18:23:38


LICENSE SYSTEM [2020410 11:1:24] 163aee45fa3744c5947d0632fa8575a9 != d39b8e2f4d364b2e98b06afa0c6e08c5


LICENSE SYSTEM [2020410 11:1:24] 163aee45fa3744c5947d0632fa8575a9 != d39b8e2f4d364b2e98b06afa0c6e08c5

DisplayProgressbar: Unity license
[UnityConnectServicesConfig] config is NOT valid, switching to default
[Licensing::Module] License is not active (com.unity.editor.ui). HasEntitlements will fail.
```

Make sure you are using a license that is generated following the readme: You must use the same version of unity when [requesting](https://github.com/marketplace/actions/unity-request-activation-file) your activation file. Please also note that [my personal license](https://github.com/backtrace-labs/backtrace-unity/pull/14/commits/1e49dd140d4515a825d99c233e948356581720e4#diff-90829e76e906f1c73140c7ded7e1b268R11) is not intended for copy pasting, and will not work on the version you're trying to run it on either.

**Comment by konraddysput** [comment]
@webbertakken 

I pushed my internal changes to visible repository. You can access my changes on my own public branch now with valid license file. My intention here was to publish something that is easy to reproduce and with your copy paste configuration I though this will be the best example. 

Internal branch run:
https://github.com/konraddysput/backtrace-unity/pull/1/checks?check_run_id=577195402

However  you pointed Unity version `2019.2.11f`. I saw that my unity license file starts with `Unity_v2017`, which suggests that this is a license for Unity 2017 - I didn't note that earlier. I will back to you if I will recognize how to generate license for Untiy 2019.

**Comment by webbertakken** [comment]
@konraddysput did you manage to get it to work?

**Comment by konraddysput** [comment]
@webbertakken still no luck. 

I generated new license file and started using docker images for Unity 2017 but now I see license errors before any action in container. 

@webbertakken I spent some time on recognizing how I can generate license file for Unity 2019. Do you have any advice for me? I'm using Unity hub and trying to do manual activation there, but stilll I'm getting license file that starts with "Unity_v2017.x..."

**Comment by webbertakken** [comment]
@konraddysput yes, it's described in detail in the [readme](https://github.com/webbertakken/unity-actions#setup) of this repository.

**Comment by konraddysput** [comment]
Unfortunatelly I'm now kind busy. Please don't close this thread. I will back to you with more info when I will find a moment to validate once again full flow.

Thanks!

**Comment by randomPoison** [comment]
I'm running into the same issue as the one that was originally reported: When I pass in `test-project` for the `projectPath` parameter, I can see in the log output that `/github/workspace/test-project` is being passed to the `-projectPath` command line argument, but then Unity reports that it can't find `/github/workspace/github/workspace/test-project`. Here's the relevant bits of the log output:

```
Run webbertakken/unity-test-runner@v1.3
  with:
    projectPath: test-project
    unityVersion: 2019.2.11f1
  env:
    UNITY_LICENSE: ***

<...>

 COMMAND LINE ARGUMENTS:
/opt/Unity/Editor/Unity
-batchmode
-logfile
/dev/stdout
-projectPath
/github/workspace/test-project
-runTests
-testPlatform
editmode
-testResults
/github/workspace/artifacts/editmode-results.xml

Couldn't set project path to: /github/workspace/github/workspace/test-project
 
(Filename: ./Runtime/Utilities/Argv.cpp Line: 360)
```

To provide a bit more context on what I tried so far:

* I was initially trying to test against Unity 2019.3.10f1 and 2018.4.11f1, but ran into the described issue right away.
* To confirm that the builder actions work as expected, I [forked the unity-actions repo](https://github.com/randomPoison/unity-actions) and cut the workflow down to just the basic README workflow. The workflow ran as expected, you can [see the output here](https://github.com/randomPoison/unity-actions/runs/620884779?check_suite_focus=true).
* I copied the example workflow into my project and setup an empty 2019.2.11f1 project in a folder named `test-project`. This should exactly replicate the setup in the forked project, and it [ran successfully](https://github.com/kongregate/kongregate-web/runs/620928892?check_suite_focus=true).

You can see the history of my attempts, along with the log output for each build, at kongregate/kongregate-web#15.

I'm not quite sure what's going on here. My suspicion is that I'm running up against a Unity bug, rather than an issue with unity-actions specifically, since it seems like unity-actions is passing the correct path via the command line and Unity is somehow ending up in the wrong place. I'll try to keep digging in to narrow down the reproduction, but let me know if there's anything you think I should try!

**Comment by randomPoison** [comment]
Okay, I've [setup a matrix job](https://github.com/kongregate/kongregate-web/actions/runs/88715524) that has one Unity build that passes and one that fails. You can [view the workflow file](https://github.com/kongregate/kongregate-web/actions/runs/88715524/workflow) on the build job. The only differences between the runs:

* The Unity version - succeeds with 2019.2.11f1, fails with 2018.4.11f1
* The project path - succeeds with `test-project`, fails with `test-project-2018.4`
* The license - Both are setup as repo secrets, but are different license activations for the different versions.

I'm not sure how to narrow the reproduction further. I haven't been able to reproduce on 2019.2.11f1, but the issue happens on every other version of Unity that I've tried so far. I'm thinking that the issue isn't a bug in Unity, at at least not a version-specific bug, because I've seen it happen in versions both before and after 2019.2.11f1.

**Comment by randomPoison** [comment]
The only other difference I could think of between the project that was working and the one that wasn't was that I had added my package as a dependency to 2018.4 test project. So I recreated that project from scratch and the build started working. Even once I added my package back as a dependency the build still worked. You can see the build that's working [here](https://github.com/kongregate/kongregate-web/actions/runs/88740847) (the 2019.211 build technically failed, but that was because tests failed and not because the project failed load).

I'm not really sure what to make of this. As far as I can tell I've recreated the original setup that was failing but now it's working and I can't tell what's different 🤷

**Comment by webbertakken** [comment]
Feel free to reopen if anyone has very similar issues.

**Comment by cadop** [comment]
I am not sure I understand what the solution here was.  I am getting the same double folders when using the online template.  The project is just an empty scene with a plane + cube, if that matters?

```
###########################
#   Testing in EditMode   #
###########################
LICENSE SYSTEM [20201216 10:11:21] Next license update check is after 2020-12-17T13:41:54

[Package Manager] Server::Start -- Port 52985 was selected

 COMMAND LINE ARGUMENTS:
/opt/Unity/Editor/Unity
-batchmode
-logfile
/dev/stdout
-projectPath
/github/workspace/UnityProject
-runTests
-testPlatform
editmode
-testResults
/github/workspace/artifacts/editmode-results.xml

Couldn't set project path to: /github/workspace/github/workspace/UnityProject
 
(Filename: ./Runtime/Utilities/Argv.cpp Line: 358)


Aborting batchmode due to failure:
Couldn't set project path to: /github/workspace/github/workspace/UnityProject

Unexpected exit code 1
```

The .yml file (just what I think are the relevant parts to save space)
```

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
            - UnityProject
        unityVersion:
            - 2019.1.3f1
    steps:
      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          projectPath: ${{matrix.projectPath}}
          unityVersion: ${{ matrix.unityVersion }}
```

Is it related to the warning?
![image](https://user-images.githubusercontent.com/11399119/102368215-9c945100-3f88-11eb-8913-c8d5133f5d0f.png)

**Comment by GabLeRoux** [comment]
@cadop the warning relates to https://github.com/game-ci/unity-actions/issues/71
Most likely unrelated to your problem. Feel free to contribute :)

**Comment by cadop** [comment]
@GabLeRoux  If I could figure it out, I would absolutely contribute :)

**Comment by webbertakken** [comment]
Did you try the latest version, just in case?

**Comment by cadop** [comment]
Latest version of Unity? - no
I did copy everything from the documentation, so maybe I put something that wasn't the latest of game-ci?

**Comment by webbertakken** [comment]
I meant the latest version of test runner.

**Comment by GabLeRoux** [comment]
https://github.com/game-ci/unity-test-runner/releases

**Comment by cadop** [comment]
@GabLeRoux  thanks for the link, it took me a bit to find it :D 

1.7 gives similar issue:
![image](https://user-images.githubusercontent.com/11399119/102392180-c22f5380-3fa4-11eb-9c5a-8156888a0fd1.png)


v2 alpha gives a different error, activation is passing, so I am not sure this is happening before or after the folder error 

![image](https://user-images.githubusercontent.com/11399119/102391212-66b09600-3fa3-11eb-8d3b-bf1287d8f393.png)

**Comment by GabLeRoux** [comment]
Docker image used changed from versions to versions. New docker image requires a new activation. Make sure you update all related actions that may use the new docker image and go through activation again.

**Comment by cadop** [comment]
@GabLeRoux  is there some document that shows where these other actions are? i.e., does `webbertakken/unity-request-manual-activation-file@v1.1` need to be changed to something else? Otherwise isn't the action the same?

**Comment by webbertakken** [comment]
I recently moved all my actions to GameCI. The old link should work just fine.

Please not that you're asking that question on the umbrella repo for the all unity actions (this very repository), and the links are all in the readme.

**Comment by cadop** [comment]
I removed the secrets file and redid the entire process with the same license error failure (not sure I even got the project path point).  

Using:
```
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2.0-alpha-1
        with:
          projectPath: ${{matrix.projectPath}}
          unityVersion: ${{ matrix.unityVersion }}
```

I use this for the activation to get the artifact.  

```
name: Acquire activation file
on: [push]
jobs:
  activation:
    name: Request manual activation file 
    runs-on: ubuntu-latest
    steps:
    # Request manual activation file
    - name: Request manual activation file
      id: getManualLicenseFile
      uses: game-ci/unity-request-activation-file/@v1.2
      with:
        unityVersion: 2019.1.3f1
        
    # Upload artifact (Unity_v20XX.X.XXXX.alf)
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
```

The license error seems to be failing to match `<MachineBindings>` thats are in the `.ulf` file. 

Anything else I am missing?

**Comment by cadop** [comment]
ugh sorry about that. I didn't see the alpha version. for some reason the other repos would show it when I clicked on releases, but that one I had to click twice.  

Anyway, now the license is working, but same error:

![image](https://user-images.githubusercontent.com/11399119/102523403-801a1680-4065-11eb-9ef7-576e25947e8c.png)

**Comment by webbertakken** [comment]
Thanks for checking this on the latest version with the new images.

I'll have a look what's different from unity builder at some point. Builder does not seem to have this problem.

**Comment by txema-martinez-scopely** [comment]
Same problem here:
<img width="833" alt="Screenshot 2021-03-16 at 15 59 32" src="https://user-images.githubusercontent.com/67916558/111331078-d8ff4800-8670-11eb-9564-59c765cf6c57.png">

Using:
```
      - uses: game-ci/unity-test-runner@v1.7
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: test
          unityVersion: 2018.4.30f1
```

**Comment by webbertakken** [comment]
@txema-martinez-scopely and your project resides in a folder `/test` that's in the root of your repository?

**Comment by txema-martinez-scopely** [comment]
> @txema-martinez-scopely and your project resides in a folder `/test` that's in the root of your repository?

I changed the path to a fake one to post the comment here, but with the real one (which is something like `ProjectName.Foo.Bar.Unity`) I get the same error.
And yes, my Unity project is in that `ProjectName.Foo.Bar.Unity` folder in the root of my repo.

**Comment by webbertakken** [comment]
> And yes, my Unity project is in that `ProjectName.Foo.Bar.Unity` folder in the root of my repo.

Could you please provide the real name? I'm asking because it is very hard to determine the cause based on assumptions. Maybe spaces, maybe special characters, may be nesting, may be trailing slash and so on. 

We have plenty of examples where `test` would just work. I'll try to help you find out why it doesn't work in your case.

**Comment by txema-martinez-scopely** [comment]
Sorry, the problem seemed to be that the Unity project was configured with a different Unity version than the one I configured in the GH action. 
Now, I see other errors.

**Comment by EricBatlle** [comment]
I'm having the same issues, this is the test-repo: https://github.com/EricBatlle/GithubActions-tests

And this is my github action file:

```
# This is a basic workflow to help you get started with Actions

name: Build

on:
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        unityVersion:
          - 2020.3.8f1
        targetPlatform:
          - Android
          - StandaloneWindows64
          #- iOS
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false
      #- name: Free disk space
        #run: .github/workflows/scripts/free_disk_space.sh
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2.1.3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - name: Git LFS Pull
        run: git lfs pull
      - uses: actions/cache@v2.1.3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: testRunner
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
      - uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}
      - uses: game-ci/unity-builder@v2
        id: buildStep
        with:
          # customParameters: -developmentBuild
          # buildMethod: UnityBuilderAction.BuildScript.Build
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          buildName: BaseDefender
          allowDirtyBuild: true
      - name: Rename build
        run: sudo mv build/Android/BaseDefender.apk build/Android/BaseDefender${{ steps.buildStep.outputs.buildVersion }}.apk
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
```

**Comment by Zh4rsiest** [comment]
For anyone that has their project files in the root folder of their repository and encounters the 
```
Project settings file not found at "ProjectSettings/ProjectVersion.txt". Have you correctly set the projectPath?
```
error, these are the things that helped me. Add projectPath as `./` and also add your project's `unityVersion`. I'm not sure why this is, it might be a bug, but even though the `ProjectSettings/ProjectVersion.txt` file exists in the repository, the action wasn't able to read it. Therefor, adding the `unityVersion` parameter, no reading of the file was needed

```
matrix:
  projectPath:
    - ./
  unityVersion:
    - 2021.3.10f1
```

```
- uses: game-ci/unity-test-runner@v2
  id: tests
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    projectPath: ${{ matrix.projectPath }}
    unityVersion: ${{ matrix.unityVersion }}
```

**Comment by webbertakken** [comment]
> For anyone that has their project files in the root folder of their repository and encounters the

This comment is misleading. 

`protjectPath` is `./` by default.
`unityVersion` is autodetected. 

Most people use these defaults without specifying them. I believe this is a user error and not a bug in test runner. 

My guess is that you had the following defined, without matrix, causing empty values to be passed (overriding the defaults). Or something similar.
```
  with:
    projectPath: ${{ matrix.projectPath }}
    unityVersion: ${{ matrix.unityVersion }}
```

**Comment by Zh4rsiest** [comment]
> My guess is that you had the following defined, without matrix, causing empty values to be passed (overriding the defaults). Or something similar.

Indeed, you are right. I did a test with removing `projectPath` and `unityVersion` from the test runner and it didn't fail. You can delete my comments above to not confuse others
